name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-wasm:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout from repo
        uses: actions/checkout@v5
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.7
      - name: Set up wasm-pack and build
        run: |
          cargo install wasm-pack
          wasm-pack build --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wgputoy-wasm
          path: pkg
